spring:
    application:
        name: loja
    profiles:
        active: dev
    config:
        import: configserver:http://localhost:8888
    #  cloud:
    #    config:
    #      label: branch-name
