spring:
    application:
        name: loja
    profiles:
        active: dev
    config:
        import: configserver:http://localhost:8888
    graphql:
        schema:
            printer:
                enabled: true
            locations:
                - classpath:graphql/

        graphiql:
            enabled: true

    output:
        ansi:
            enabled: ALWAYS
    #  cloud:
    #    config:
    #      label: branch-name
